### PR TITLE
fixed factor 2 missing in FrequencyRampPulse

### PR DESCRIPTION
**Pull request by RostyslavSavytskyy**

### CODE REVIEW

**Comment by nulinspiratie** [comment]
@maij @RostyslavSavytskyy Did anyone actually check that the frequency was indeed off by a factor 2?

**Comment by nulinspiratie** [comment]
As in look at the pulse sequence and verify that the final frequency is lower than it should be?

**Comment by nulinspiratie** [comment]
Nevermind, I verified and it was indeed off

**Comment by RostyslavSavytskyy** [comment]
I can just add that with this factor of 2, the adiabatic peak had the correct width

**Pull request merged**
